const moduleData = {
  rfq: {
    eyebrow: 'WORKSPACE / RFQ MANAGEMENT',
    title: 'RFQ management',
    description: 'Create, track, and close requests for quotation across every department.',
    action: 'Create RFQ',
    stats: [['Open requests', '24', '↑ 12.5%'], ['Awaiting quotes', '18', '↑ 8.2%'], ['Closing this week', '06', '3 urgent'], ['Completed', '42', 'This quarter']],
    headers: ['RFQ ID', 'Material', 'Quantity', 'Department', 'Deadline', 'Vendors', 'Status'],
    rows: [['RFQ-2026-0042', 'Silicon Wafer 300mm', '1,000 pcs', 'Manufacturing', 'Sep 01, 2026', '8', 'Open'], ['RFQ-2026-0041', 'Microcontrollers', '4,500 pcs', 'Engineering', 'Aug 28, 2026', '12', 'Pending'], ['RFQ-2026-0039', 'Pressure Sensors', '850 pcs', 'Quality', 'Aug 25, 2026', '6', 'Completed'], ['RFQ-2026-0038', 'Electronic Components', '12,000 pcs', 'Operations', 'Aug 21, 2026', '9', 'Closed']]
  },
  vendors: {
    eyebrow: 'WORKSPACE / VENDORS', title: 'Vendor directory', description: 'Manage approved suppliers and monitor their performance over time.', action: 'Add vendor',
    stats: [['Approved vendors', '128', '↑ 6 this month'], ['Top performers', '34', 'Above 90% score'], ['Under review', '07', 'Needs attention'], ['Avg. reliability', '92%', '↑ 3.4% this year']],
    headers: ['Vendor', 'Category', 'Contact', 'Rating', 'Orders', 'Performance', 'Status'],
    rows: [['ABC Semiconductors', 'Semiconductor', 'Anika Rao', '4.9 / 5', '84', '96%', 'Approved'], ['Nova Components', 'Electronics', 'Rahul Mehta', '4.7 / 5', '62', '91%', 'Approved'], ['Precision Circuits', 'Integrated circuits', 'Maya Singh', '4.4 / 5', '38', '86%', 'Review'], ['Vertex Industrial', 'Sensors', 'Arjun Shah', '4.8 / 5', '51', '94%', 'Approved']]
  },
  quotations: {
    eyebrow: 'WORKSPACE / QUOTATIONS', title: 'Quotation inbox', description: 'Review incoming supplier quotes and move the strongest offers forward.', action: 'Upload quote',
    stats: [['Received', '18', 'Across 6 RFQs'], ['AI extracted', '14', '78% automated'], ['Manual review', '04', 'Requires action'], ['Avg. response', '2.4d', '↓ 0.6 days']],
    headers: ['Quotation', 'Vendor', 'RFQ', 'Quoted value', 'Delivery', 'Extraction', 'Status'],
    rows: [['QT-2026-0108', 'ABC Semiconductors', 'RFQ-0042', '₹8,50,000', '7 days', 'Validated', 'Received'], ['QT-2026-0107', 'Nova Components', 'RFQ-0042', '₹8,10,000', '15 days', 'Validated', 'Received'], ['QT-2026-0106', 'Precision Circuits', 'RFQ-0041', '₹12,40,000', '10 days', 'Manual review', 'Review'], ['QT-2026-0105', 'Vertex Industrial', 'RFQ-0039', '₹4,85,000', '6 days', 'Validated', 'Selected']]
  },
  'vendor-comparison': {
    eyebrow: 'WORKSPACE / VENDOR COMPARISON', title: 'Compare suppliers', description: 'Make a confident sourcing decision with transparent weighted scoring.', action: 'Configure weights',
    stats: [['Suppliers compared', '04', 'RFQ-2026-0042'], ['Recommended', 'ABC', '93.0% overall'], ['Within budget', '03', 'Of 4 suppliers'], ['Delivery risk', '01', 'Needs review']],
    headers: ['Supplier', 'Price score', 'Delivery', 'Reliability', 'Quality', 'Final score', 'Recommendation'],
    rows: [['ABC Semiconductors', '90%', '98%', '95%', '92%', '93.0%', 'Recommended'], ['Nova Components', '96%', '76%', '88%', '87%', '87.3%', 'Alternative'], ['Precision Circuits', '84%', '90%', '91%', '95%', '89.5%', 'Alternative'], ['Vertex Industrial', '88%', '99%', '82%', '84%', '87.8%', 'Review']]
  },
  'purchase-orders': {
    eyebrow: 'OPERATIONS / PURCHASE ORDERS', title: 'Purchase orders', description: 'Track approvals, delivery commitments, and the full purchase order lifecycle.', action: 'Create PO',
    stats: [['Active orders', '12', '₹24.5L committed'], ['Awaiting approval', '02', '₹7.8L value'], ['In delivery', '08', 'On schedule'], ['Delivered', '46', 'This quarter']],
    headers: ['PO number', 'Vendor', 'Items', 'Total value', 'Expected delivery', 'Approval', 'Status'],
    rows: [['PO-2026-018', 'ABC Semiconductors', 'Silicon Wafer', '₹8,50,000', 'Sep 01, 2026', 'Approved', 'In delivery'], ['PO-2026-017', 'Nova Components', 'Microcontrollers', '₹4,20,000', 'Aug 28, 2026', 'Pending', 'Processing'], ['PO-2026-016', 'Vertex Industrial', 'Sensors', '₹2,85,000', 'Aug 25, 2026', 'Approved', 'In delivery'], ['PO-2026-015', 'Precision Circuits', 'IC Components', '₹6,10,000', 'Aug 20, 2026', 'Approved', 'Delivered']]
  },
  inventory: {
    eyebrow: 'OPERATIONS / INVENTORY', title: 'Inventory control', description: 'See current stock, incoming materials, and the items that need attention.', action: 'Add material',
    stats: [['Total materials', '246', 'Across 8 categories'], ['Low stock', '05', 'Needs replenishment'], ['Out of stock', '02', 'Critical'], ['Incoming', '18,400', 'Units in transit']],
    headers: ['Material', 'Category', 'Current stock', 'Reorder level', 'Incoming', 'Stock health', 'Status'],
    rows: [['Silicon Wafer 300mm', 'Semiconductor', '200 pcs', '500 pcs', '800 pcs', '40%', 'Low stock'], ['Microcontrollers', 'Electronics', '3,200 pcs', '1,000 pcs', '4,500 pcs', 'Healthy', 'In stock'], ['Pressure Sensors', 'Sensors', '0 pcs', '250 pcs', '850 pcs', '0%', 'Critical'], ['Integrated Circuits', 'Components', '5,800 pcs', '2,000 pcs', '0 pcs', 'Healthy', 'In stock']]
  },
  finance: {
    eyebrow: 'OPERATIONS / FINANCE', title: 'Finance overview', description: 'Monitor committed spend, invoices, payment timelines, and savings.', action: 'Export report',
    stats: [['Committed spend', '₹24.5L', '↑ 18.4% this period'], ['Outstanding', '₹8.2L', '12 open invoices'], ['Paid this month', '₹6.4L', '8 transactions'], ['Savings identified', '₹3.1L', '12.6% average']],
    headers: ['Invoice', 'Purchase order', 'Vendor', 'Amount', 'Due date', 'Invoice status', 'Payment'],
    rows: [['INV-2026-0088', 'PO-2026-018', 'ABC Semiconductors', '₹8,50,000', 'Sep 30, 2026', 'Received', 'Scheduled'], ['INV-2026-0087', 'PO-2026-017', 'Nova Components', '₹4,20,000', 'Sep 15, 2026', 'Received', 'Outstanding'], ['INV-2026-0086', 'PO-2026-016', 'Vertex Industrial', '₹2,85,000', 'Sep 10, 2026', 'Paid', 'Complete'], ['INV-2026-0085', 'PO-2026-015', 'Precision Circuits', '₹6,10,000', 'Aug 20, 2026', 'Paid', 'Complete']]
  },
  approvals: {
    eyebrow: 'OPERATIONS / APPROVALS', title: 'Approval queue', description: 'Keep high-value procurement moving with a clear, accountable approval trail.', action: 'View approval rules',
    stats: [['Pending approvals', '04', '2 high value'], ['Approved today', '08', '₹12.4L cleared'], ['Average time', '3.2h', '↓ 18% this month'], ['Rejected', '01', 'Requires review']],
    headers: ['Request', 'Requester', 'Department', 'Amount', 'Submitted', 'Approver', 'Status'],
    rows: [['PO-2026-018', 'Anika Rao', 'Manufacturing', '₹8,50,000', 'Today, 09:40', 'Finance Admin', 'Pending'], ['PO-2026-017', 'Rahul Mehta', 'Engineering', '₹4,20,000', 'Today, 08:15', 'Procurement', 'Pending'], ['PO-2026-016', 'Maya Singh', 'Quality', '₹2,85,000', 'Yesterday', 'Finance Admin', 'Approved'], ['PO-2026-014', 'Arjun Shah', 'Operations', '₹1,40,000', 'Aug 18, 2026', 'Procurement', 'Rejected']]
  },
  analytics: {
    eyebrow: 'OPERATIONS / ANALYTICS', title: 'Procurement analytics', description: 'Understand spend, supplier performance, and the operational impact of every decision.', action: 'Export analytics',
    stats: [['Procurement spend', '₹24.5L', '↑ 18.4%'], ['RFQ conversion', '68%', '↑ 7.2%'], ['Average savings', '12.6%', '₹3.1L identified'], ['Approval time', '3.2h', '↓ 18%']],
    headers: ['Category', 'Spend', 'RFQs', 'Avg. savings', 'Top supplier', 'Performance', 'Trend'],
    rows: [['Semiconductors', '₹10.8L', '18', '14.2%', 'ABC Semiconductors', '96%', '↑ Growing'], ['Electronics', '₹6.4L', '12', '11.8%', 'Nova Components', '91%', '↑ Growing'], ['Sensors', '₹4.8L', '08', '9.4%', 'Vertex Industrial', '88%', '→ Stable'], ['Components', '₹2.5L', '06', '13.1%', 'Precision Circuits', '94%', '↑ Growing']]
  }
};

function statusClass(status) {
  const value = status.toLowerCase();
  if (value.includes('approved') || value.includes('selected') || value.includes('complete') || value.includes('healthy') || value.includes('recommended') || value.includes('delivered') || value.includes('in stock')) return 'approved';
  if (value.includes('critical') || value.includes('rejected') || value.includes('low stock')) return 'danger';
  if (value.includes('pending') || value.includes('review') || value.includes('processing') || value.includes('outstanding')) return 'warning';
  return 'info';
}

export function renderModulePage(moduleKey, profile) {
  const module = moduleData[moduleKey];
  if (!module) return '';
  const isAdmin = ['admin', 'manager'].includes(profile?.role);
  const actionCell = (moduleKey === 'vendors' && isAdmin)
    ? '<button class="row-action approve-action" type="button">Approve</button><button class="row-action reject-action" type="button">Reject</button>'
    : '<button class="row-action" type="button" title="View details">View</button>';
  const profileEditor = moduleKey === 'vendors' && profile?.role === 'vendor'
    ? '<section class="module-panel vendor-profile-panel" data-vendor-profile><div class="module-toolbar"><div><span class="ai-label">SUPPLIER PROFILE</span><h2>Maintain your company details</h2></div><span class="status-badge pending">Profile changes require review</span></div><form data-vendor-profile-form class="profile-form"><div><label>Company name<input name="companyName" required /></label><label>Contact<input name="contact" required /></label><label>Category<input name="category" required /></label></div><div><label>Materials supplied<input name="materials" placeholder="Silicon wafers, sensors" required /></label><label>Company information<textarea name="companyInformation" required></textarea></label></div><button class="primary-button" type="submit">Save profile <span>→</span></button><p class="form-message" data-profile-message></p></form></section>'
    : '';
  const rfqForm = moduleKey === 'rfq' && ['buyer', 'admin', 'manager'].includes(profile?.role)
    ? '<section class="module-panel rfq-form-panel"><div class="module-toolbar"><div><span class="ai-label">NEW PROCUREMENT REQUEST</span><h2>Create an RFQ</h2></div><span class="status-badge info">Draft by default</span></div><form data-rfq-form class="profile-form"><div><label>Material / item *<input name="material" placeholder="Silicon Wafer 300mm" required /></label><label>Quantity *<input name="quantity" type="number" min="1" placeholder="1000" required /></label><label>Required delivery date *<input name="deadline" type="date" required /></label></div><div><label>Budget (INR) *<input name="budget" type="number" min="1" placeholder="1000000" required /></label><label>Specifications *<textarea name="specifications" placeholder="Grade, dimensions, technical requirements" required></textarea></label><label>Additional requirements<textarea name="additionalRequirements" placeholder="Packaging, warranty, payment terms"></textarea></label></div><button class="primary-button" type="submit">Save RFQ <span>→</span></button><p class="form-message" data-rfq-message></p></form></section>'
    : '';
  const quotationForm = moduleKey === 'vendor-comparison' && ['buyer', 'admin', 'manager'].includes(profile?.role)
    ? '<section class="module-panel comparison-form-panel"><div class="module-toolbar"><div><span class="ai-label">LIVE VENDOR SCORING</span><h2>Compare RFQ quotations</h2></div><span class="status-badge info">Uses configured scoring weights</span></div><form data-comparison-form class="profile-form"><div><label>RFQ document ID *<input name="rfqId" placeholder="RFQ document ID" required /></label></div><button class="primary-button" type="submit">Calculate comparison <span>→</span></button><p class="form-message" data-comparison-message></p></form></section>'
    : moduleKey === 'vendors' && ['buyer', 'admin', 'manager'].includes(profile?.role)
    ? '<section class="module-panel vendor-directory-form"><div class="module-toolbar"><div><span class="ai-label">SUPPLIER ONBOARDING</span><h2>Add a vendor to the directory</h2></div><span class="status-badge pending">Pending review</span></div><form data-directory-vendor-form class="profile-form"><div><label>Company name *<input name="companyName" required /></label><label>Business email *<input name="email" type="email" required /></label><label>Contact number *<input name="contact" required /></label></div><div><label>Supply category *<input name="category" required /></label><label>Materials supplied *<input name="materials" placeholder="Wafers, sensors" required /></label><label>Company information<textarea name="companyInformation" placeholder="Capabilities and certifications"></textarea></label></div><button class="primary-button" type="submit">Add vendor <span>→</span></button><p class="form-message" data-directory-vendor-message></p></form></section>'
    : moduleKey === 'inventory' && ['buyer', 'admin', 'manager'].includes(profile?.role)
    ? '<section class="module-panel material-form-panel"><div class="module-toolbar"><div><span class="ai-label">MATERIAL MASTER</span><h2>Add an inventory material</h2></div><span class="status-badge info">Stock levels tracked from creation</span></div><form data-material-form class="profile-form"><div><label>Material name *<input name="name" placeholder="e.g. Silicon Wafer 300mm" required /></label><label>Category *<input name="category" placeholder="e.g. Semiconductor" required /></label><label>Current stock *<input name="currentStock" type="number" min="0" required /></label></div><div><label>Minimum stock *<input name="minimumStock" type="number" min="0" required /></label><label>Reorder level *<input name="reorderLevel" type="number" min="0" required /></label><label>Specifications<textarea name="specifications" placeholder="Grade, dimensions, storage requirements"></textarea></label></div><button class="primary-button" type="submit">Add material <span>→</span></button><p class="form-message" data-material-message></p></form></section>'
    : moduleKey === 'purchase-orders' && ['buyer', 'admin', 'manager'].includes(profile?.role)
    ? '<section class="module-panel purchase-order-form-panel"><div class="module-toolbar"><div><span class="ai-label">ORDER CREATION</span><h2>Create a purchase order</h2></div><span class="status-badge info">Requires approval before issue</span></div><form data-purchase-order-form class="profile-form"><div><label>Selected quotation ID *<input name="quotationId" placeholder="Quotation document ID" required /></label><label>Expected delivery date<input name="expectedDeliveryDate" type="date" /></label><label>Payment terms<textarea name="paymentTerms" placeholder="e.g. Net 30 days from invoice"></textarea></label></div><button class="primary-button" type="submit">Create purchase order <span>→</span></button><p class="form-message" data-purchase-order-message></p></form></section>'
    : moduleKey === 'approvals' && ['admin', 'manager'].includes(profile?.role)
    ? '<section class="module-panel approval-form-panel"><div class="module-toolbar"><div><span class="ai-label">APPROVAL DECISION</span><h2>Review a purchase order</h2></div><span class="status-badge warning">Manager approval required</span></div><form data-approval-form class="profile-form"><div><label>Purchase order *<input name="purchaseOrderId" placeholder="e.g. PO-2026-018" required /></label><label>Decision *<select name="status" required><option value="approved">Approve</option><option value="rejected">Reject</option></select></label><label>Decision notes<textarea name="comments" placeholder="Add a reason or approval note"></textarea></label></div><button class="primary-button" type="submit">Save decision <span>→</span></button><p class="form-message" data-approval-message></p></form></section>'
    : moduleKey === 'finance' && ['buyer', 'admin', 'manager'].includes(profile?.role)
    ? '<section class="module-panel finance-form-panel"><div class="module-toolbar"><div><span class="ai-label">BALANCE TRACKER</span><h2>Create an invoice balance</h2></div><span class="status-badge info">Balance calculated automatically</span></div><form data-finance-form class="profile-form"><div><label>Purchase order *<input name="purchaseOrderId" placeholder="e.g. PO-2026-018" required /></label><label>Invoice number *<input name="invoiceNumber" placeholder="INV-2026-0089" required /></label><label>Due date *<input name="paymentDueDate" type="date" required /></label></div><div><label>Invoice amount (INR) *<input name="amount" data-balance-amount type="number" min="1" step="0.01" required /></label><label>Tax (INR)<input name="tax" data-balance-tax type="number" min="0" step="0.01" value="0" /></label><label>Amount paid (INR)<input name="paidAmount" data-balance-paid type="number" min="0" step="0.01" value="0" /></label></div><div class="balance-result"><span>Total invoice <strong data-balance-total>₹0.00</strong></span><span>Remaining balance <strong data-balance-outstanding>₹0.00</strong></span></div><button class="primary-button" type="submit">Create balance record <span>→</span></button><p class="form-message" data-finance-message></p></form></section>'
    : moduleKey === 'quotations' && ['buyer', 'vendor', 'admin', 'manager'].includes(profile?.role)
    ? '<section class="module-panel quotation-form-panel"><div class="module-toolbar"><div><span class="ai-label">MANUAL + AI EXTRACTION</span><h2>Submit a quotation</h2></div><span class="status-badge info">PDF sent directly to Gemini</span></div><form data-quotation-form class="profile-form"><div><label>RFQ ID *<input name="rfqId" placeholder="RFQ-2026-0042" required /></label><label>Quotation PDF (optional)<input name="quotationPdf" type="file" accept="application/pdf" /></label><label>Price (INR) *<input name="price" type="number" min="1" required /></label><label>Quantity *<input name="quantity" type="number" min="1" required /></label><label>Delivery date *<input name="deliveryDate" type="date" required /></label></div><div><label>Delivery days *<input name="deliveryDays" type="number" min="0" required /></label><label>Validity *<input name="validity" placeholder="30 days" required /></label><label>Quality score *<input name="quality" type="number" min="0" max="100" required /></label><label>Specifications *<textarea name="specifications" required></textarea></label></div><button class="primary-button" type="submit">Submit quotation <span>→</span></button><p class="form-message" data-quotation-message></p></form></section>'
    : '';
  return `<main class="module-content"><div class="module-heading"><div><p class="eyebrow">${module.eyebrow}</p><h1>${module.title}</h1><p>${module.description}</p></div><button class="create-button" type="button"><span>+</span>${module.action}</button></div>${rfqForm}${profileEditor}${quotationForm}<section class="metric-grid module-metrics">${module.stats.map(([label, value, trend], index) => `<article class="metric-card"><div class="metric-icon ${['blue', 'amber', 'violet', 'red'][index]}">${['↗', '≡', '□', '◇'][index]}</div><span class="metric-label">${label}</span><strong>${value}</strong><small class="trend ${index === 3 ? 'warning' : 'positive'}">${trend}</small></article>`).join('')}</section><section class="module-panel"><div class="module-toolbar"><div><span class="ai-label">LIVE WORKSPACE DATA</span><h2>${module.title} records</h2></div><div class="table-tools"><input placeholder="Search records..." aria-label="Search records" /><select aria-label="Filter records"><option>All statuses</option><option>Approved</option><option>Pending</option><option>Needs review</option></select></div></div><div class="table-wrap"><table><thead><tr>${module.headers.map((header) => `<th>${header}</th>`).join('')}<th>Action</th></tr></thead><tbody>${module.rows.map((row) => `<tr>${row.map((cell, index) => `<td class="${index === row.length - 1 ? `status-cell ${statusClass(cell)}` : ''}">${index === row.length - 1 ? `<span class="status-badge ${statusClass(cell)}">${cell}</span>` : cell}</td>`).join('')}<td>${actionCell}</td></tr>`).join('')}</tbody></table></div><div class="table-footer"><span>Showing ${module.rows.length} of ${module.rows.length * 8} records</span><div><button class="page-button" type="button">←</button><button class="page-button is-current" type="button">1</button><button class="page-button" type="button">2</button><button class="page-button" type="button">→</button></div></div></section></main>`;
}
